[package]
edition = "2018"
name = "deleteSnip"
version = "0.1.0"

[dependencies]
postgrest = "1.0"
serde_json = "1.0.83"
dotenv = "0.15.0"
aws_lambda_events = "0.6.3"
http = "0.2.8"
lambda_runtime = "0.6.0"
log = "0.4.17"
simple_logger = "1.16.0"
tokio = "1.20.1"

